// Generated from late-ssh/src/app/common/theme.rs.
// Keep this file data-only: the app reads window.PRESET_THEMES.
window.PRESET_THEMES = [
  {
    "id": "contrast",
    "label": "High Contrast",
    "group": "Core",
    "kind": "Contrast",
    "colors": {
      "bg_canvas": "#2a2c34",
      "bg_selection": "#1a1e26",
      "bg_highlight": "#222832",
      "border_dim": "#4a5462",
      "border": "#738296",
      "border_active": "#7ac9ff",
      "text_faint": "#7e8a9b",
      "text_dim": "#a4b0c1",
      "text_muted": "#c2cddc",
      "text": "#e2eaf5",
      "text_bright": "#f8fbff",
      "amber": "#ffc45c",
      "amber_dim": "#d6a04b",
      "amber_glow": "#ffd87f",
      "chat_body": "#ecf2fa",
      "chat_author": "#90cfff",
      "mention": "#ffe57a",
      "success": "#83d691",
      "error": "#ff8585",
      "bot": "#ab88ff",
      "bonsai_sprout": "#7dcf76",
      "bonsai_leaf": "#8fe07d",
      "bonsai_canopy": "#a8eb89",
      "bonsai_bloom": "#d6f4b0",
      "badge_bronze": "#c9985a",
      "badge_silver": "#d6dce4",
      "badge_gold": "#ffd666"
    }
  },
  {
    "id": "late",
    "label": "Late",
    "group": "Core",
    "kind": "Late",
    "colors": {
      "bg_canvas": "#000000",
      "bg_selection": "#1e1916",
      "bg_highlight": "#28211c",
      "border_dim": "#322a24",
      "border": "#44382e",
      "border_active": "#a0692a",
      "text_faint": "#4e4136",
      "text_dim": "#695848",
      "text_muted": "#8a7660",
      "text": "#af9e8a",
      "text_bright": "#c8b69e",
      "amber": "#b8782c",
      "amber_dim": "#825826",
      "amber_glow": "#d29436",
      "chat_body": "#beb2a5",
      "chat_author": "#8ca0af",
      "mention": "#e4c44e",
      "success": "#648c48",
      "error": "#a84238",
      "bot": "#875faf",
      "bonsai_sprout": "#588244",
      "bonsai_leaf": "#649448",
      "bonsai_canopy": "#76a252",
      "bonsai_bloom": "#aac378",
      "badge_bronze": "#a07846",
      "badge_silver": "#b4b4b4",
      "badge_gold": "#dcb432"
    }
  },
  {
    "id": "purple",
    "label": "Purple Haze",
    "group": "Core",
    "kind": "Purple",
    "colors": {
      "bg_canvas": "#37394c",
      "bg_selection": "#2c1a42",
      "bg_highlight": "#3a2354",
      "border_dim": "#5c487a",
      "border": "#7e65a6",
      "border_active": "#ffabf7",
      "text_faint": "#b09dc7",
      "text_dim": "#c9b8de",
      "text_muted": "#dccfec",
      "text": "#eee7f7",
      "text_bright": "#fcf8ff",
      "amber": "#ffb86c",
      "amber_dim": "#d68d5d",
      "amber_glow": "#ffd091",
      "chat_body": "#f4eefa",
      "chat_author": "#9ce9d0",
      "mention": "#ffdf82",
      "success": "#95dfaa",
      "error": "#ff94b5",
      "bot": "#c295ff",
      "bonsai_sprout": "#82d28e",
      "bonsai_leaf": "#93e39f",
      "bonsai_canopy": "#aeeeaa",
      "bonsai_bloom": "#dcf8c4",
      "badge_bronze": "#cd9d6e",
      "badge_silver": "#e5dfef",
      "badge_gold": "#ffdb7a"
    }
  },
  {
    "id": "mocha",
    "label": "Catppuccin Mocha",
    "group": "Catppuccin",
    "kind": "Mocha",
    "colors": {
      "bg_canvas": "#1e1e2e",
      "bg_selection": "#45475a",
      "bg_highlight": "#181825",
      "border_dim": "#313244",
      "border": "#585b70",
      "border_active": "#cba6f7",
      "text_faint": "#6c7086",
      "text_dim": "#9399b2",
      "text_muted": "#a6adc8",
      "text": "#cdd6f4",
      "text_bright": "#f5e0dc",
      "amber": "#fab387",
      "amber_dim": "#c88123",
      "amber_glow": "#f9e2af",
      "chat_body": "#cdd6f4",
      "chat_author": "#89b4fa",
      "mention": "#f5c2e7",
      "success": "#a6e3a1",
      "error": "#f38ba8",
      "bot": "#b4befe",
      "bonsai_sprout": "#94e2d5",
      "bonsai_leaf": "#a6e3a1",
      "bonsai_canopy": "#89dceb",
      "bonsai_bloom": "#cba6f7",
      "badge_bronze": "#eba078",
      "badge_silver": "#bac2de",
      "badge_gold": "#f9e2af"
    }
  },
  {
    "id": "macchiato",
    "label": "Catppuccin Macchiato",
    "group": "Catppuccin",
    "kind": "Macchiato",
    "colors": {
      "bg_canvas": "#24273a",
      "bg_selection": "#414559",
      "bg_highlight": "#1e2030",
      "border_dim": "#2e3147",
      "border": "#494d64",
      "border_active": "#c6a0f6",
      "text_faint": "#6e738d",
      "text_dim": "#a5adcb",
      "text_muted": "#b8c0e0",
      "text": "#cad3f5",
      "text_bright": "#f4dbd6",
      "amber": "#f5a97f",
      "amber_dim": "#c3774d",
      "amber_glow": "#eed49f",
      "chat_body": "#cad3f5",
      "chat_author": "#8aadf4",
      "mention": "#f5bde6",
      "success": "#a6da95",
      "error": "#ed8796",
      "bot": "#b7bdf8",
      "bonsai_sprout": "#91d7e3",
      "bonsai_leaf": "#a6da95",
      "bonsai_canopy": "#91d7e3",
      "bonsai_bloom": "#c6a0f6",
      "badge_bronze": "#ee9972",
      "badge_silver": "#aeb6d3",
      "badge_gold": "#eed49f"
    }
  },
  {
    "id": "frappe",
    "label": "Catppuccin Frappé",
    "group": "Catppuccin",
    "kind": "Frappe",
    "colors": {
      "bg_canvas": "#303446",
      "bg_selection": "#51576d",
      "bg_highlight": "#292c3c",
      "border_dim": "#414559",
      "border": "#626880",
      "border_active": "#ca9ee6",
      "text_faint": "#737994",
      "text_dim": "#a5acc4",
      "text_muted": "#b5bfe2",
      "text": "#c6d0f5",
      "text_bright": "#f2d5cf",
      "amber": "#ef9f76",
      "amber_dim": "#bd6d44",
      "amber_glow": "#e5c890",
      "chat_body": "#c6d0f5",
      "chat_author": "#8caaee",
      "mention": "#f4b8e4",
      "success": "#a6d189",
      "error": "#e78284",
      "bot": "#babbf1",
      "bonsai_sprout": "#81c8be",
      "bonsai_leaf": "#a6d189",
      "bonsai_canopy": "#99d1db",
      "bonsai_bloom": "#ca9ee6",
      "badge_bronze": "#e7916a",
      "badge_silver": "#adb8d8",
      "badge_gold": "#e5c890"
    }
  },
  {
    "id": "latte",
    "label": "Catppuccin Latte",
    "group": "Catppuccin",
    "kind": "Latte",
    "colors": {
      "bg_canvas": "#eff1f5",
      "bg_selection": "#acb0be",
      "bg_highlight": "#bcc0cc",
      "border_dim": "#ccd0da",
      "border": "#9ca0b0",
      "border_active": "#8839ef",
      "text_faint": "#8c8fa1",
      "text_dim": "#5c5f77",
      "text_muted": "#4c4f69",
      "text": "#4c4f69",
      "text_bright": "#dc8a78",
      "amber": "#fe640b",
      "amber_dim": "#cc3200",
      "amber_glow": "#df8e1d",
      "chat_body": "#4c4f69",
      "chat_author": "#1e66f5",
      "mention": "#ea76cb",
      "success": "#40a02b",
      "error": "#d20f39",
      "bot": "#7287fd",
      "bonsai_sprout": "#179299",
      "bonsai_leaf": "#40a02b",
      "bonsai_canopy": "#04a5e5",
      "bonsai_bloom": "#8839ef",
      "badge_bronze": "#e64553",
      "badge_silver": "#9ca0b0",
      "badge_gold": "#df8e1d"
    }
  },
  {
    "id": "egg_coffee",
    "label": "Egg Coffee",
    "group": "Coffee",
    "kind": "EggCoffee",
    "colors": {
      "bg_canvas": "#1a0f0d",
      "bg_selection": "#3d2620",
      "bg_highlight": "#9d6e3b",
      "border_dim": "#402d28",
      "border": "#5c4640",
      "border_active": "#ecb854",
      "text_faint": "#786964",
      "text_dim": "#aa9b96",
      "text_muted": "#d2c3be",
      "text": "#f9f1e7",
      "text_bright": "#fffcf9",
      "amber": "#ecb854",
      "amber_dim": "#b48c41",
      "amber_glow": "#ffdc8c",
      "chat_body": "#ebe1d7",
      "chat_author": "#ecb854",
      "mention": "#fff0b4",
      "success": "#ecb854",
      "error": "#9e3228",
      "bot": "#968ce6",
      "bonsai_sprout": "#8ca078",
      "bonsai_leaf": "#788c64",
      "bonsai_canopy": "#647850",
      "bonsai_bloom": "#ecb854",
      "badge_bronze": "#b18c59",
      "badge_silver": "#b4b9be",
      "badge_gold": "#ecb854"
    }
  },
  {
    "id": "americano",
    "label": "Americano",
    "group": "Coffee",
    "kind": "Americano",
    "colors": {
      "bg_canvas": "#141212",
      "bg_selection": "#232020",
      "bg_highlight": "#2a2626",
      "border_dim": "#373232",
      "border": "#554e4e",
      "border_active": "#8d7d77",
      "text_faint": "#645f5f",
      "text_dim": "#8c8787",
      "text_muted": "#b4afaf",
      "text": "#d2cdcd",
      "text_bright": "#eceff4",
      "amber": "#a1887f",
      "amber_dim": "#795548",
      "amber_glow": "#bcaaa4",
      "chat_body": "#c8c3c3",
      "chat_author": "#8d7d77",
      "mention": "#aed581",
      "success": "#8d7d77",
      "error": "#bf616a",
      "bot": "#b4befe",
      "bonsai_sprout": "#a3be8c",
      "bonsai_leaf": "#8fa878",
      "bonsai_canopy": "#768c62",
      "bonsai_bloom": "#eceff4",
      "badge_bronze": "#8d7d77",
      "badge_silver": "#b8c0cc",
      "badge_gold": "#ebcb8b"
    }
  },
  {
    "id": "espresso",
    "label": "Espresso",
    "group": "Coffee",
    "kind": "Espresso",
    "colors": {
      "bg_canvas": "#0a0807",
      "bg_selection": "#241a17",
      "bg_highlight": "#1f1a18",
      "border_dim": "#3a2823",
      "border": "#543a32",
      "border_active": "#d2691e",
      "text_faint": "#645550",
      "text_dim": "#968782",
      "text_muted": "#c8beb9",
      "text": "#f5f5f5",
      "text_bright": "#ffffff",
      "amber": "#d2691e",
      "amber_dim": "#8b4513",
      "amber_glow": "#ffa500",
      "chat_body": "#f0f0f0",
      "chat_author": "#d2691e",
      "mention": "#ffd700",
      "success": "#d2691e",
      "error": "#ff4646",
      "bot": "#b4a0ff",
      "bonsai_sprout": "#6b8e23",
      "bonsai_leaf": "#556b2f",
      "bonsai_canopy": "#8b4513",
      "bonsai_bloom": "#d2691e",
      "badge_bronze": "#8b4513",
      "badge_silver": "#c0c0c0",
      "badge_gold": "#ffd700"
    }
  },
  {
    "id": "gruvboxdark",
    "label": "Gruvbox Dark",
    "group": "Ports",
    "kind": "GruvboxDark",
    "colors": {
      "bg_canvas": "#282828",
      "bg_selection": "#3c3836",
      "bg_highlight": "#1d2021",
      "border_dim": "#504945",
      "border": "#665c54",
      "border_active": "#d65d0e",
      "text_faint": "#928374",
      "text_dim": "#a89984",
      "text_muted": "#bdae93",
      "text": "#ebdbb2",
      "text_bright": "#fbf1c7",
      "amber": "#d79921",
      "amber_dim": "#af7c0c",
      "amber_glow": "#fabd2f",
      "chat_body": "#ebdbb2",
      "chat_author": "#b8bb26",
      "mention": "#d3869b",
      "success": "#b8bb26",
      "error": "#fb4934",
      "bot": "#83a598",
      "bonsai_sprout": "#8ec07c",
      "bonsai_leaf": "#b8bb26",
      "bonsai_canopy": "#83a598",
      "bonsai_bloom": "#fb4934",
      "badge_bronze": "#d65d0e",
      "badge_silver": "#a89984",
      "badge_gold": "#fabd2f"
    }
  },
  {
    "id": "onedarkpro",
    "label": "One Dark Pro",
    "group": "Ports",
    "kind": "OneDarkPro",
    "colors": {
      "bg_canvas": "#1e2127",
      "bg_selection": "#2c323c",
      "bg_highlight": "#181a1f",
      "border_dim": "#373f4b",
      "border": "#4b5362",
      "border_active": "#4db5ff",
      "text_faint": "#545b69",
      "text_dim": "#8c96aa",
      "text_muted": "#abb2bf",
      "text": "#dbe2ef",
      "text_bright": "#ef596f",
      "amber": "#ebba5b",
      "amber_dim": "#b48c3c",
      "amber_glow": "#ebba5b",
      "chat_body": "#dbe2ef",
      "chat_author": "#d55fde",
      "mention": "#4ebcca",
      "success": "#8dc165",
      "error": "#ef596f",
      "bot": "#4db5ff",
      "bonsai_sprout": "#4ebcca",
      "bonsai_leaf": "#8dc165",
      "bonsai_canopy": "#4db5ff",
      "bonsai_bloom": "#d55fde",
      "badge_bronze": "#e0985a",
      "badge_silver": "#dbe2ef",
      "badge_gold": "#ebba5b"
    }
  },
  {
    "id": "rosepine",
    "label": "Rose Pine",
    "group": "Ports",
    "kind": "RosePine",
    "colors": {
      "bg_canvas": "#191724",
      "bg_selection": "#403d52",
      "bg_highlight": "#1f1d2e",
      "border_dim": "#6e6a86",
      "border": "#9c99af",
      "border_active": "#ebbcba",
      "text_faint": "#6e6a86",
      "text_dim": "#9c99af",
      "text_muted": "#e0def4",
      "text": "#e0def4",
      "text_bright": "#eb6f92",
      "amber": "#f6c177",
      "amber_dim": "#c48f45",
      "amber_glow": "#f6c177",
      "chat_body": "#e0def4",
      "chat_author": "#c4a7e7",
      "mention": "#ebbcba",
      "success": "#31748f",
      "error": "#eb6f92",
      "bot": "#9ccfd8",
      "bonsai_sprout": "#9ccfd8",
      "bonsai_leaf": "#31748f",
      "bonsai_canopy": "#9ccfd8",
      "bonsai_bloom": "#c4a7e7",
      "badge_bronze": "#eb6f92",
      "badge_silver": "#e0def4",
      "badge_gold": "#f6c177"
    }
  },
  {
    "id": "tokyonight",
    "label": "Tokyo Night",
    "group": "Ports",
    "kind": "TokyoNight",
    "colors": {
      "bg_canvas": "#24283b",
      "bg_selection": "#292e42",
      "bg_highlight": "#1a1b26",
      "border_dim": "#3b4261",
      "border": "#565f89",
      "border_active": "#7aa2f7",
      "text_faint": "#565f89",
      "text_dim": "#a9b1d6",
      "text_muted": "#c0caf5",
      "text": "#c0caf5",
      "text_bright": "#bb9af7",
      "amber": "#e0af68",
      "amber_dim": "#b88740",
      "amber_glow": "#e0af68",
      "chat_body": "#c0caf5",
      "chat_author": "#2ac3de",
      "mention": "#ff9e64",
      "success": "#9ece6a",
      "error": "#f7768e",
      "bot": "#7aa2f7",
      "bonsai_sprout": "#73daca",
      "bonsai_leaf": "#9ece6a",
      "bonsai_canopy": "#7aa2f7",
      "bonsai_bloom": "#bb9af7",
      "badge_bronze": "#ff9e64",
      "badge_silver": "#c0caf5",
      "badge_gold": "#e0af68"
    }
  },
  {
    "id": "kanagawa",
    "label": "Kanagawa",
    "group": "Ports",
    "kind": "Kanagawa",
    "colors": {
      "bg_canvas": "#1f1f28",
      "bg_selection": "#2d2d3b",
      "bg_highlight": "#16161d",
      "border_dim": "#36364b",
      "border": "#54527a",
      "border_active": "#7e96bd",
      "text_faint": "#727185",
      "text_dim": "#9c9c9c",
      "text_muted": "#d2c9a6",
      "text": "#d2c9a6",
      "text_bright": "#e6b450",
      "amber": "#ffa066",
      "amber_dim": "#c4703c",
      "amber_glow": "#ffa066",
      "chat_body": "#d2c9a6",
      "chat_author": "#98bb6c",
      "mention": "#957bab",
      "success": "#98bb6c",
      "error": "#c47272",
      "bot": "#7e96bd",
      "bonsai_sprout": "#7aa298",
      "bonsai_leaf": "#98bb6c",
      "bonsai_canopy": "#7e96bd",
      "bonsai_bloom": "#957bab",
      "badge_bronze": "#c4703c",
      "badge_silver": "#727185",
      "badge_gold": "#e6b450"
    }
  },
  {
    "id": "dracula",
    "label": "Dracula",
    "group": "Ports",
    "kind": "Dracula",
    "colors": {
      "bg_canvas": "#282a36",
      "bg_selection": "#44475a",
      "bg_highlight": "#21222c",
      "border_dim": "#44475a",
      "border": "#6272a4",
      "border_active": "#bd93f9",
      "text_faint": "#6272a4",
      "text_dim": "#8b97bd",
      "text_muted": "#f8f8f2",
      "text": "#f8f8f2",
      "text_bright": "#ff79c6",
      "amber": "#f1fa8c",
      "amber_dim": "#bfc85a",
      "amber_glow": "#f1fa8c",
      "chat_body": "#f8f8f2",
      "chat_author": "#8be9fd",
      "mention": "#ffb86c",
      "success": "#50fa7b",
      "error": "#ff5555",
      "bot": "#bd93f9",
      "bonsai_sprout": "#8be9fd",
      "bonsai_leaf": "#50fa7b",
      "bonsai_canopy": "#bd93f9",
      "bonsai_bloom": "#ff79c6",
      "badge_bronze": "#ffb86c",
      "badge_silver": "#f8f8f2",
      "badge_gold": "#f1fa8c"
    }
  },
  {
    "id": "oxocarbon",
    "label": "Oxocarbon",
    "group": "Ports",
    "kind": "Oxocarbon",
    "colors": {
      "bg_canvas": "#161616",
      "bg_selection": "#262626",
      "bg_highlight": "#0e0e0e",
      "border_dim": "#393939",
      "border": "#525252",
      "border_active": "#3db8ff",
      "text_faint": "#525252",
      "text_dim": "#b6b6b6",
      "text_muted": "#f2f4f8",
      "text": "#f2f4f8",
      "text_bright": "#ff7eb6",
      "amber": "#be95ff",
      "amber_dim": "#8c63cd",
      "amber_glow": "#be95ff",
      "chat_body": "#f2f4f8",
      "chat_author": "#3db8ff",
      "mention": "#33ffb8",
      "success": "#3db8ff",
      "error": "#ff7eb6",
      "bot": "#be95ff",
      "bonsai_sprout": "#33ffb8",
      "bonsai_leaf": "#3db8ff",
      "bonsai_canopy": "#be95ff",
      "bonsai_bloom": "#ff7eb6",
      "badge_bronze": "#ff7eb6",
      "badge_silver": "#f2f4f8",
      "badge_gold": "#be95ff"
    }
  },
  {
    "id": "copperfresh",
    "label": "Copper Fresh",
    "group": "Copper",
    "kind": "CopperFresh",
    "colors": {
      "bg_canvas": "#140c0a",
      "bg_selection": "#2d1914",
      "bg_highlight": "#0c0807",
      "border_dim": "#3c231e",
      "border": "#64372d",
      "border_active": "#ff7d50",
      "text_faint": "#5a3c37",
      "text_dim": "#a0786e",
      "text_muted": "#d2b4aa",
      "text": "#f0e1dc",
      "text_bright": "#ffb48c",
      "amber": "#ff8c3c",
      "amber_dim": "#96461e",
      "amber_glow": "#ffb464",
      "chat_body": "#f0e1dc",
      "chat_author": "#ff7d50",
      "mention": "#ffc896",
      "success": "#d2643c",
      "error": "#be281e",
      "bot": "#d26e5a",
      "bonsai_sprout": "#b45a46",
      "bonsai_leaf": "#8c3c2d",
      "bonsai_canopy": "#140c0a",
      "bonsai_bloom": "#ffb48c",
      "badge_bronze": "#8c4632",
      "badge_silver": "#bebebe",
      "badge_gold": "#ffb48c"
    }
  },
  {
    "id": "exposedcopper",
    "label": "Exposed Copper",
    "group": "Copper",
    "kind": "ExposedCopper",
    "colors": {
      "bg_canvas": "#120e0c",
      "bg_selection": "#281e19",
      "bg_highlight": "#0a0807",
      "border_dim": "#372823",
      "border": "#554137",
      "border_active": "#b46e55",
      "text_faint": "#504641",
      "text_dim": "#8c7d78",
      "text_muted": "#c8beb9",
      "text": "#e1d7d2",
      "text_bright": "#e6a082",
      "amber": "#a05a46",
      "amber_dim": "#6e3c2d",
      "amber_glow": "#c88264",
      "chat_body": "#e1d7d2",
      "chat_author": "#b46e55",
      "mention": "#be8c78",
      "success": "#646e5a",
      "error": "#a0322d",
      "bot": "#8c7369",
      "bonsai_sprout": "#6e7864",
      "bonsai_leaf": "#555f50",
      "bonsai_canopy": "#120e0c",
      "bonsai_bloom": "#e6a082",
      "badge_bronze": "#6e3c2d",
      "badge_silver": "#aaaaaa",
      "badge_gold": "#e6a082"
    }
  },
  {
    "id": "weatheredcopper",
    "label": "Weathered Copper",
    "group": "Copper",
    "kind": "WeatheredCopper",
    "colors": {
      "bg_canvas": "#0c1210",
      "bg_selection": "#1e2d28",
      "bg_highlight": "#080c0a",
      "border_dim": "#2d3c37",
      "border": "#465a55",
      "border_active": "#50b4a0",
      "text_faint": "#4b5550",
      "text_dim": "#829691",
      "text_muted": "#bed2cd",
      "text": "#d7e6e1",
      "text_bright": "#78ffdc",
      "amber": "#468c78",
      "amber_dim": "#285a50",
      "amber_glow": "#64c8b4",
      "chat_body": "#d7e6e1",
      "chat_author": "#50b4a0",
      "mention": "#78c8be",
      "success": "#50c8a0",
      "error": "#b44646",
      "bot": "#5a968c",
      "bonsai_sprout": "#6ea096",
      "bonsai_leaf": "#4b786e",
      "bonsai_canopy": "#0c1210",
      "bonsai_bloom": "#78ffdc",
      "badge_bronze": "#0c1210",
      "badge_silver": "#a0a0a0",
      "badge_gold": "#78ffdc"
    }
  },
  {
    "id": "oxidizedcopper",
    "label": "Oxidized Copper",
    "group": "Copper",
    "kind": "OxidizedCopper",
    "colors": {
      "bg_canvas": "#080f0f",
      "bg_selection": "#142828",
      "bg_highlight": "#050a0a",
      "border_dim": "#233c3c",
      "border": "#3c6464",
      "border_active": "#00ffdc",
      "text_faint": "#3c5a5a",
      "text_dim": "#82b4b4",
      "text_muted": "#bee6e6",
      "text": "#dcfafa",
      "text_bright": "#64fff0",
      "amber": "#32dcbe",
      "amber_dim": "#1e8c78",
      "amber_glow": "#64ffe6",
      "chat_body": "#dcfafa",
      "chat_author": "#00ffdc",
      "mention": "#96fff5",
      "success": "#00ffb4",
      "error": "#dc5050",
      "bot": "#50dcc8",
      "bonsai_sprout": "#82ffd2",
      "bonsai_leaf": "#32b4a0",
      "bonsai_canopy": "#080f0f",
      "bonsai_bloom": "#64fff0",
      "badge_bronze": "#080f0f",
      "badge_silver": "#c8dcdc",
      "badge_gold": "#64fff0"
    }
  },
  {
    "id": "arachne",
    "label": "Arachne",
    "group": "MARATHON",
    "kind": "Arachne",
    "colors": {
      "bg_canvas": "#050505",
      "bg_selection": "#280000",
      "bg_highlight": "#0f0000",
      "border_dim": "#6c0004",
      "border": "#b00000",
      "border_active": "#ce0724",
      "text_faint": "#501414",
      "text_dim": "#963232",
      "text_muted": "#d1d1d1",
      "text": "#d1d1d1",
      "text_bright": "#ce0724",
      "amber": "#b00000",
      "amber_dim": "#6c0004",
      "amber_glow": "#ce0724",
      "chat_body": "#d1d1d1",
      "chat_author": "#ce0724",
      "mention": "#ce0724",
      "success": "#b00000",
      "error": "#ce0724",
      "bot": "#6c0004",
      "bonsai_sprout": "#b00000",
      "bonsai_leaf": "#6c0004",
      "bonsai_canopy": "#050505",
      "bonsai_bloom": "#ce0724",
      "badge_bronze": "#6c0004",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ce0724"
    }
  },
  {
    "id": "cyberacme",
    "label": "CyberAcme",
    "group": "MARATHON",
    "kind": "CyberAcme",
    "colors": {
      "bg_canvas": "#050505",
      "bg_selection": "#0a1432",
      "bg_highlight": "#050a19",
      "border_dim": "#1a12ed",
      "border": "#26ea5b",
      "border_active": "#5bf9fe",
      "text_faint": "#1a12ed",
      "text_dim": "#26ea5b",
      "text_muted": "#d1d1d1",
      "text": "#d1d1d1",
      "text_bright": "#5bf9fe",
      "amber": "#26ea5b",
      "amber_dim": "#1a12ed",
      "amber_glow": "#5bf9fe",
      "chat_body": "#d1d1d1",
      "chat_author": "#26ea5b",
      "mention": "#5bf9fe",
      "success": "#26ea5b",
      "error": "#1a12ed",
      "bot": "#5bf9fe",
      "bonsai_sprout": "#5bf9fe",
      "bonsai_leaf": "#26ea5b",
      "bonsai_canopy": "#050505",
      "bonsai_bloom": "#1a12ed",
      "badge_bronze": "#1a12ed",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#5bf9fe"
    }
  },
  {
    "id": "nucaloric",
    "label": "NuCaloric",
    "group": "MARATHON",
    "kind": "NuCaloric",
    "colors": {
      "bg_canvas": "#050505",
      "bg_selection": "#320a14",
      "bg_highlight": "#19050a",
      "border_dim": "#a60424",
      "border": "#fa6196",
      "border_active": "#ffe48e",
      "text_faint": "#a60424",
      "text_dim": "#fa6196",
      "text_muted": "#d1d1d1",
      "text": "#d1d1d1",
      "text_bright": "#ffe48e",
      "amber": "#fa6196",
      "amber_dim": "#a60424",
      "amber_glow": "#ffe48e",
      "chat_body": "#d1d1d1",
      "chat_author": "#fa6196",
      "mention": "#ffe48e",
      "success": "#fa6196",
      "error": "#a60424",
      "bot": "#ffe48e",
      "bonsai_sprout": "#ffe48e",
      "bonsai_leaf": "#fa6196",
      "bonsai_canopy": "#050505",
      "bonsai_bloom": "#a60424",
      "badge_bronze": "#a60424",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffe48e"
    }
  },
  {
    "id": "sekiguchi",
    "label": "Sekiguchi",
    "group": "MARATHON",
    "kind": "Sekiguchi",
    "colors": {
      "bg_canvas": "#050505",
      "bg_selection": "#190a28",
      "bg_highlight": "#0c0514",
      "border_dim": "#54179b",
      "border": "#7556b5",
      "border_active": "#82f5bb",
      "text_faint": "#54179b",
      "text_dim": "#7556b5",
      "text_muted": "#d1d1d1",
      "text": "#d1d1d1",
      "text_bright": "#82f5bb",
      "amber": "#7556b5",
      "amber_dim": "#54179b",
      "amber_glow": "#82f5bb",
      "chat_body": "#d1d1d1",
      "chat_author": "#7556b5",
      "mention": "#82f5bb",
      "success": "#82f5bb",
      "error": "#54179b",
      "bot": "#7556b5",
      "bonsai_sprout": "#82f5bb",
      "bonsai_leaf": "#7556b5",
      "bonsai_canopy": "#050505",
      "bonsai_bloom": "#54179b",
      "badge_bronze": "#54179b",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#82f5bb"
    }
  },
  {
    "id": "traxus",
    "label": "Traxus",
    "group": "MARATHON",
    "kind": "Traxus",
    "colors": {
      "bg_canvas": "#050505",
      "bg_selection": "#3c1e00",
      "bg_highlight": "#190c00",
      "border_dim": "#903703",
      "border": "#ee7f00",
      "border_active": "#ff9e00",
      "text_faint": "#903703",
      "text_dim": "#ee7f00",
      "text_muted": "#d1d1d1",
      "text": "#d1d1d1",
      "text_bright": "#ff9e00",
      "amber": "#ff9e00",
      "amber_dim": "#ee7f00",
      "amber_glow": "#ffc864",
      "chat_body": "#d1d1d1",
      "chat_author": "#ff9e00",
      "mention": "#ff9e00",
      "success": "#ee7f00",
      "error": "#903703",
      "bot": "#ff9e00",
      "bonsai_sprout": "#ff9e00",
      "bonsai_leaf": "#ee7f00",
      "bonsai_canopy": "#050505",
      "bonsai_bloom": "#903703",
      "badge_bronze": "#903703",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ff9e00"
    }
  },
  {
    "id": "mida",
    "label": "Mida",
    "group": "MARATHON",
    "kind": "Mida",
    "colors": {
      "bg_canvas": "#050505",
      "bg_selection": "#0f1928",
      "bg_highlight": "#080c14",
      "border_dim": "#225c84",
      "border": "#cb6df6",
      "border_active": "#ccd6b3",
      "text_faint": "#225c84",
      "text_dim": "#cb6df6",
      "text_muted": "#d1d1d1",
      "text": "#d1d1d1",
      "text_bright": "#ccd6b3",
      "amber": "#e38041",
      "amber_dim": "#225c84",
      "amber_glow": "#ccd6b3",
      "chat_body": "#d1d1d1",
      "chat_author": "#cb6df6",
      "mention": "#e38041",
      "success": "#ccd6b3",
      "error": "#e38041",
      "bot": "#cb6df6",
      "bonsai_sprout": "#ccd6b3",
      "bonsai_leaf": "#cb6df6",
      "bonsai_canopy": "#050505",
      "bonsai_bloom": "#e38041",
      "badge_bronze": "#225c84",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ccd6b3"
    }
  },
  {
    "id": "ena",
    "label": "ENA",
    "group": "JoelG",
    "kind": "ENA",
    "colors": {
      "bg_canvas": "#050505",
      "bg_selection": "#295ff7",
      "bg_highlight": "#0f1423",
      "border_dim": "#295ff7",
      "border": "#fde701",
      "border_active": "#e3cfb6",
      "text_faint": "#295ff7",
      "text_dim": "#fde701",
      "text_muted": "#b4b4b4",
      "text": "#d1d1d1",
      "text_bright": "#e3cfb6",
      "amber": "#fde701",
      "amber_dim": "#295ff7",
      "amber_glow": "#e3cfb6",
      "chat_body": "#d1d1d1",
      "chat_author": "#fde701",
      "mention": "#e3cfb6",
      "success": "#fde701",
      "error": "#ff0032",
      "bot": "#e3cfb6",
      "bonsai_sprout": "#e3cfb6",
      "bonsai_leaf": "#295ff7",
      "bonsai_canopy": "#050505",
      "bonsai_bloom": "#fde701",
      "badge_bronze": "#295ff7",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#e3cfb6"
    }
  },
  {
    "id": "enadreambbq",
    "label": "ENA Dream BBQ",
    "group": "JoelG",
    "kind": "ENADreamBbq",
    "colors": {
      "bg_canvas": "#050505",
      "bg_selection": "#155e55",
      "bg_highlight": "#0a2320",
      "border_dim": "#5b8694",
      "border": "#e6838c",
      "border_active": "#f1e6c6",
      "text_faint": "#155e55",
      "text_dim": "#8fb7c6",
      "text_muted": "#d1d1d1",
      "text": "#d1d1d1",
      "text_bright": "#f1e6c6",
      "amber": "#e13f3d",
      "amber_dim": "#8fb7c6",
      "amber_glow": "#f1e6c6",
      "chat_body": "#d1d1d1",
      "chat_author": "#e6838c",
      "mention": "#f1e6c6",
      "success": "#8fb7c6",
      "error": "#e13f3d",
      "bot": "#f1e6c6",
      "bonsai_sprout": "#f1e6c6",
      "bonsai_leaf": "#155e55",
      "bonsai_canopy": "#050505",
      "bonsai_bloom": "#e13f3d",
      "badge_bronze": "#155e55",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#f1e6c6"
    }
  },
  {
    "id": "kirii",
    "label": "Kirii",
    "group": "Experimental",
    "kind": "Kirii",
    "colors": {
      "bg_canvas": "#0f0159",
      "bg_selection": "#0d0063",
      "bg_highlight": "#1c0f4a",
      "border_dim": "#2925ff",
      "border": "#b78dff",
      "border_active": "#ff99dd",
      "text_faint": "#2925ff",
      "text_dim": "#b78dff",
      "text_muted": "#b4b4b4",
      "text": "#d1d1d1",
      "text_bright": "#d4fffa",
      "amber": "#ff99dd",
      "amber_dim": "#2925ff",
      "amber_glow": "#d4fffa",
      "chat_body": "#d1d1d1",
      "chat_author": "#ff99dd",
      "mention": "#d4fffa",
      "success": "#d4fffa",
      "error": "#ff0050",
      "bot": "#b78dff",
      "bonsai_sprout": "#ff99dd",
      "bonsai_leaf": "#2925ff",
      "bonsai_canopy": "#050505",
      "bonsai_bloom": "#d4fffa",
      "badge_bronze": "#0d0063",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ff99dd"
    }
  },
  {
    "id": "discord-dark",
    "label": "Discord",
    "group": "SocialDark",
    "kind": "DiscordDark",
    "colors": {
      "bg_canvas": "#1a1a1e",
      "bg_selection": "#0f1e90",
      "bg_highlight": "#2d3055",
      "border_dim": "#848bd7",
      "border": "#4752c4",
      "border_active": "#ffffff",
      "text_faint": "#848bd7",
      "text_dim": "#96979e",
      "text_muted": "#b4b4dc",
      "text": "#e6e6fa",
      "text_bright": "#ffffff",
      "amber": "#5865f2",
      "amber_dim": "#ea9800",
      "amber_glow": "#ffffff",
      "chat_body": "#e6e6fa",
      "chat_author": "#5865f2",
      "mention": "#ffffff",
      "success": "#45a366",
      "error": "#f23f43",
      "bot": "#5865f2",
      "bonsai_sprout": "#23a55a",
      "bonsai_leaf": "#00a8fc",
      "bonsai_canopy": "#ffc04e",
      "bonsai_bloom": "#f23f43",
      "badge_bronze": "#b48228",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffffff"
    }
  },
  {
    "id": "facebook-dark",
    "label": "Facebook",
    "group": "SocialDark",
    "kind": "FacebookDark",
    "colors": {
      "bg_canvas": "#1b1b1c",
      "bg_selection": "#0866ff",
      "bg_highlight": "#080130",
      "border_dim": "#004cc2",
      "border": "#0866ff",
      "border_active": "#ffffff",
      "text_faint": "#004cc2",
      "text_dim": "#0866ff",
      "text_muted": "#b4b4dc",
      "text": "#e6e6fa",
      "text_bright": "#ffffff",
      "amber": "#a5afba",
      "amber_dim": "#646e78",
      "amber_glow": "#ffffff",
      "chat_body": "#e6e6fa",
      "chat_author": "#0866ff",
      "mention": "#ffc04e",
      "success": "#4fc06a",
      "error": "#f02849",
      "bot": "#fa97ff",
      "bonsai_sprout": "#31a24c",
      "bonsai_leaf": "#0866ff",
      "bonsai_canopy": "#ffc04e",
      "bonsai_bloom": "#fa97ff",
      "badge_bronze": "#646e78",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffffff"
    }
  },
  {
    "id": "twitter-dark",
    "label": "Twitter",
    "group": "SocialDark",
    "kind": "TwitterDark",
    "colors": {
      "bg_canvas": "#141d26",
      "bg_selection": "#1464a0",
      "bg_highlight": "#080130",
      "border_dim": "#1464a0",
      "border": "#1d9bf0",
      "border_active": "#ffffff",
      "text_faint": "#1464a0",
      "text_dim": "#1d9bf0",
      "text_muted": "#b4b4dc",
      "text": "#e6e6fa",
      "text_bright": "#ffffff",
      "amber": "#1d9bf0",
      "amber_dim": "#1464a0",
      "amber_glow": "#ffffff",
      "chat_body": "#e6e6fa",
      "chat_author": "#1d9bf0",
      "mention": "#ffffff",
      "success": "#1d9bf0",
      "error": "#ff0032",
      "bot": "#459fb5",
      "bonsai_sprout": "#1d9bf0",
      "bonsai_leaf": "#1464a0",
      "bonsai_canopy": "#080130",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#1464a0",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffffff"
    }
  },
  {
    "id": "telegram-dark",
    "label": "Telegram",
    "group": "SocialDark",
    "kind": "TelegramDark",
    "colors": {
      "bg_canvas": "#212d3b",
      "bg_selection": "#196e9b",
      "bg_highlight": "#080130",
      "border_dim": "#196e9b",
      "border": "#24a1de",
      "border_active": "#ffffff",
      "text_faint": "#196e9b",
      "text_dim": "#24a1de",
      "text_muted": "#b4b4dc",
      "text": "#e6e6fa",
      "text_bright": "#ffffff",
      "amber": "#24a1de",
      "amber_dim": "#196e9b",
      "amber_glow": "#ffffff",
      "chat_body": "#e6e6fa",
      "chat_author": "#24a1de",
      "mention": "#ffffff",
      "success": "#24a1de",
      "error": "#ff0032",
      "bot": "#24a1de",
      "bonsai_sprout": "#24a1de",
      "bonsai_leaf": "#196e9b",
      "bonsai_canopy": "#080130",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#196e9b",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffffff"
    }
  },
  {
    "id": "github-dark",
    "label": "GitHub",
    "group": "SocialDark",
    "kind": "GitHubDark",
    "colors": {
      "bg_canvas": "#0d1117",
      "bg_selection": "#262c36",
      "bg_highlight": "#151b23",
      "border_dim": "#30363d",
      "border": "#383f48",
      "border_active": "#ffffff",
      "text_faint": "#8b949e",
      "text_dim": "#8b949e",
      "text_muted": "#b4b4dc",
      "text": "#e6e6fa",
      "text_bright": "#ffffff",
      "amber": "#4493f8",
      "amber_dim": "#8b949e",
      "amber_glow": "#ffffff",
      "chat_body": "#e6e6fa",
      "chat_author": "#e6e6fa",
      "mention": "#ffffff",
      "success": "#238636",
      "error": "#f85149",
      "bot": "#9198a1",
      "bonsai_sprout": "#238636",
      "bonsai_leaf": "#30363d",
      "bonsai_canopy": "#f78166",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#30363d",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffffff"
    }
  },
  {
    "id": "discord-light",
    "label": "Discord",
    "group": "SocialLight",
    "kind": "DiscordLight",
    "colors": {
      "bg_canvas": "#f2f2f2",
      "bg_selection": "#d2d7ff",
      "bg_highlight": "#e0e0e0",
      "border_dim": "#b4b9e6",
      "border": "#5865f2",
      "border_active": "#2e3338",
      "text_faint": "#646e78",
      "text_dim": "#4e545c",
      "text_muted": "#5f646e",
      "text": "#2e3338",
      "text_bright": "#000000",
      "amber": "#5865f2",
      "amber_dim": "#a06e14",
      "amber_glow": "#818bf7",
      "chat_body": "#2e3338",
      "chat_author": "#5865f2",
      "mention": "#4752c4",
      "success": "#23a55a",
      "error": "#f23f43",
      "bot": "#5865f2",
      "bonsai_sprout": "#23a55a",
      "bonsai_leaf": "#00a8fc",
      "bonsai_canopy": "#8b95fa",
      "bonsai_bloom": "#f23f43",
      "badge_bronze": "#a06e14",
      "badge_silver": "#787878",
      "badge_gold": "#daa520"
    }
  },
  {
    "id": "facebook-light",
    "label": "Facebook",
    "group": "SocialLight",
    "kind": "FacebookLight",
    "colors": {
      "bg_canvas": "#f0f2f5",
      "bg_selection": "#e7f3ff",
      "bg_highlight": "#dcdee1",
      "border_dim": "#b4b9c3",
      "border": "#0866ff",
      "border_active": "#1c1e21",
      "text_faint": "#65676b",
      "text_dim": "#0866ff",
      "text_muted": "#828791",
      "text": "#1c1e21",
      "text_bright": "#000000",
      "amber": "#65676b",
      "amber_dim": "#8c9196",
      "amber_glow": "#ffffff",
      "chat_body": "#1c1e21",
      "chat_author": "#0866ff",
      "mention": "#a333ff",
      "success": "#31a24c",
      "error": "#f02849",
      "bot": "#a333ff",
      "bonsai_sprout": "#31a24c",
      "bonsai_leaf": "#0866ff",
      "bonsai_canopy": "#dcdee1",
      "bonsai_bloom": "#a333ff",
      "badge_bronze": "#8c9196",
      "badge_silver": "#787878",
      "badge_gold": "#daa520"
    }
  },
  {
    "id": "twitter-light",
    "label": "Twitter",
    "group": "SocialLight",
    "kind": "TwitterLight",
    "colors": {
      "bg_canvas": "#ffffff",
      "bg_selection": "#e6f5ff",
      "bg_highlight": "#f7f9fa",
      "border_dim": "#cfd9de",
      "border": "#1d9bf0",
      "border_active": "#0f1419",
      "text_faint": "#536471",
      "text_dim": "#1d9bf0",
      "text_muted": "#78828c",
      "text": "#0f1419",
      "text_bright": "#000000",
      "amber": "#ffad1f",
      "amber_dim": "#c8820a",
      "amber_glow": "#ffffff",
      "chat_body": "#0f1419",
      "chat_author": "#1d9bf0",
      "mention": "#1d9bf0",
      "success": "#00ba7c",
      "error": "#f91880",
      "bot": "#1d9bf0",
      "bonsai_sprout": "#00ba7c",
      "bonsai_leaf": "#1d9bf0",
      "bonsai_canopy": "#f7f9fa",
      "bonsai_bloom": "#f91880",
      "badge_bronze": "#78828c",
      "badge_silver": "#b4b4b4",
      "badge_gold": "#ffad1f"
    }
  },
  {
    "id": "telegram-light",
    "label": "Telegram",
    "group": "SocialLight",
    "kind": "TelegramLight",
    "colors": {
      "bg_canvas": "#ffffff",
      "bg_selection": "#e1ebf5",
      "bg_highlight": "#f0f5fa",
      "border_dim": "#b4c8dc",
      "border": "#24a1de",
      "border_active": "#141e28",
      "text_faint": "#78828c",
      "text_dim": "#24a1de",
      "text_muted": "#707579",
      "text": "#000000",
      "text_bright": "#141e28",
      "amber": "#24a1de",
      "amber_dim": "#196e9b",
      "amber_glow": "#ffffff",
      "chat_body": "#000000",
      "chat_author": "#24a1de",
      "mention": "#24a1de",
      "success": "#4aba6c",
      "error": "#e84949",
      "bot": "#24a1de",
      "bonsai_sprout": "#4aba6c",
      "bonsai_leaf": "#24a1de",
      "bonsai_canopy": "#f0f5fa",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#b4c8dc",
      "badge_silver": "#969696",
      "badge_gold": "#daa520"
    }
  },
  {
    "id": "github-light",
    "label": "GitHub",
    "group": "SocialLight",
    "kind": "GitHubLight",
    "colors": {
      "bg_canvas": "#ffffff",
      "bg_selection": "#eaeef2",
      "bg_highlight": "#f6f8fa",
      "border_dim": "#d0d7de",
      "border": "#1f2328",
      "border_active": "#0969da",
      "text_faint": "#57606a",
      "text_dim": "#1f2328",
      "text_muted": "#646e78",
      "text": "#1f2328",
      "text_bright": "#000000",
      "amber": "#0969da",
      "amber_dim": "#57606a",
      "amber_glow": "#ffffff",
      "chat_body": "#1f2328",
      "chat_author": "#1f2328",
      "mention": "#0969da",
      "success": "#1a7f37",
      "error": "#cf222e",
      "bot": "#57606a",
      "bonsai_sprout": "#1a7f37",
      "bonsai_leaf": "#1f2328",
      "bonsai_canopy": "#f6f8fa",
      "bonsai_bloom": "#cf222e",
      "badge_bronze": "#af8205",
      "badge_silver": "#787878",
      "badge_gold": "#daa520"
    }
  },
  {
    "id": "matcha",
    "label": "Matcha",
    "group": "Tea",
    "kind": "Matcha",
    "colors": {
      "bg_canvas": "#0a140a",
      "bg_selection": "#446114",
      "bg_highlight": "#050a05",
      "border_dim": "#283c1e",
      "border": "#9cd73c",
      "border_active": "#ffffff",
      "text_faint": "#506446",
      "text_dim": "#9cd73c",
      "text_muted": "#b4beaa",
      "text": "#e6f0e6",
      "text_bright": "#ffffff",
      "amber": "#d2b43c",
      "amber_dim": "#8c7828",
      "amber_glow": "#ffffff",
      "chat_body": "#e6f0e6",
      "chat_author": "#9cd73c",
      "mention": "#ffffff",
      "success": "#9cd73c",
      "error": "#dc3c3c",
      "bot": "#9cd73c",
      "bonsai_sprout": "#9cd73c",
      "bonsai_leaf": "#283c1e",
      "bonsai_canopy": "#050a05",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#8c7828",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffffff"
    }
  },
  {
    "id": "earlgrey",
    "label": "Earl Grey",
    "group": "Tea",
    "kind": "EarlGrey",
    "colors": {
      "bg_canvas": "#0f0f14",
      "bg_selection": "#614f15",
      "bg_highlight": "#08080c",
      "border_dim": "#3c4150",
      "border": "#5078c8",
      "border_active": "#d4af37",
      "text_faint": "#646978",
      "text_dim": "#5078c8",
      "text_muted": "#aaafbe",
      "text": "#e6e6f0",
      "text_bright": "#ffffff",
      "amber": "#d4af37",
      "amber_dim": "#96781e",
      "amber_glow": "#ffffff",
      "chat_body": "#e6e6f0",
      "chat_author": "#5078c8",
      "mention": "#ffffff",
      "success": "#64a064",
      "error": "#c85050",
      "bot": "#5078c8",
      "bonsai_sprout": "#d4af37",
      "bonsai_leaf": "#5078c8",
      "bonsai_canopy": "#08080c",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#96781e",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#d4af37"
    }
  },
  {
    "id": "hibiscus",
    "label": "Hibiscus",
    "group": "Tea",
    "kind": "Hibiscus",
    "colors": {
      "bg_canvas": "#28050f",
      "bg_selection": "#a1021f",
      "bg_highlight": "#140208",
      "border_dim": "#781e3c",
      "border": "#ff2864",
      "border_active": "#ffffff",
      "text_faint": "#963c5a",
      "text_dim": "#6f062e",
      "text_muted": "#dcb4be",
      "text": "#fae6eb",
      "text_bright": "#ffffff",
      "amber": "#eb6c44",
      "amber_dim": "#b45014",
      "amber_glow": "#ffffff",
      "chat_body": "#fae6eb",
      "chat_author": "#ff2864",
      "mention": "#ffffff",
      "success": "#28dc78",
      "error": "#ff0032",
      "bot": "#ff2864",
      "bonsai_sprout": "#ff2864",
      "bonsai_leaf": "#781e3c",
      "bonsai_canopy": "#140208",
      "bonsai_bloom": "#ffc8dc",
      "badge_bronze": "#b45014",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffffff"
    }
  },
  {
    "id": "oolong",
    "label": "Oolong",
    "group": "Tea",
    "kind": "Oolong",
    "colors": {
      "bg_canvas": "#190f0a",
      "bg_selection": "#c87828",
      "bg_highlight": "#0f0805",
      "border_dim": "#50321e",
      "border": "#c87828",
      "border_active": "#ffc864",
      "text_faint": "#6e503c",
      "text_dim": "#623b13",
      "text_muted": "#beaa96",
      "text": "#f0e6dc",
      "text_bright": "#ffffff",
      "amber": "#ffb432",
      "amber_dim": "#966414",
      "amber_glow": "#ffffff",
      "chat_body": "#f0e6dc",
      "chat_author": "#c87828",
      "mention": "#ffffff",
      "success": "#8ca032",
      "error": "#b43c28",
      "bot": "#c87828",
      "bonsai_sprout": "#c87828",
      "bonsai_leaf": "#50321e",
      "bonsai_canopy": "#0f0805",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#966414",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffb432"
    }
  },
  {
    "id": "silverneedle",
    "label": "Silver Needle",
    "group": "Tea",
    "kind": "SilverNeedle",
    "colors": {
      "bg_canvas": "#1e2323",
      "bg_selection": "#646e6e",
      "bg_highlight": "#141919",
      "border_dim": "#465050",
      "border": "#b4c3c3",
      "border_active": "#ffffff",
      "text_faint": "#465050",
      "text_dim": "#b4c3c3",
      "text_muted": "#a0aaaa",
      "text": "#dce6e6",
      "text_bright": "#ffffff",
      "amber": "#e6f0c8",
      "amber_dim": "#96a078",
      "amber_glow": "#ffffff",
      "chat_body": "#dce6e6",
      "chat_author": "#b4c3c3",
      "mention": "#ffffff",
      "success": "#a0c896",
      "error": "#c88282",
      "bot": "#b4c3c3",
      "bonsai_sprout": "#b4c3c3",
      "bonsai_leaf": "#465050",
      "bonsai_canopy": "#141919",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#96a078",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffffff"
    }
  },
  {
    "id": "crt-amber",
    "label": "CRT Amber",
    "group": "Crt",
    "kind": "CrtAmber",
    "colors": {
      "bg_canvas": "#0f0a00",
      "bg_selection": "#9b4c00",
      "bg_highlight": "#1e1400",
      "border_dim": "#644600",
      "border": "#ffb000",
      "border_active": "#ffe696",
      "text_faint": "#644600",
      "text_dim": "#ffb000",
      "text_muted": "#b48200",
      "text": "#ffbe28",
      "text_bright": "#ffe696",
      "amber": "#ffb000",
      "amber_dim": "#785000",
      "amber_glow": "#ffd264",
      "chat_body": "#ffbe28",
      "chat_author": "#ffb000",
      "mention": "#ffffff",
      "success": "#ffb000",
      "error": "#ff3200",
      "bot": "#ffb000",
      "bonsai_sprout": "#ffb000",
      "bonsai_leaf": "#644600",
      "bonsai_canopy": "#1e1400",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#644600",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffb000"
    }
  },
  {
    "id": "crt-green",
    "label": "CRT Green",
    "group": "Crt",
    "kind": "CrtGreen",
    "colors": {
      "bg_canvas": "#000f05",
      "bg_selection": "#009b23",
      "bg_highlight": "#001e0a",
      "border_dim": "#00641e",
      "border": "#00ff41",
      "border_active": "#96ffb4",
      "text_faint": "#00641e",
      "text_dim": "#00ff41",
      "text_muted": "#00b432",
      "text": "#32ff64",
      "text_bright": "#96ffb4",
      "amber": "#00ff41",
      "amber_dim": "#005014",
      "amber_glow": "#c8ffc8",
      "chat_body": "#32ff64",
      "chat_author": "#00ff41",
      "mention": "#ffffff",
      "success": "#00ff41",
      "error": "#ff0000",
      "bot": "#00ff41",
      "bonsai_sprout": "#00ff41",
      "bonsai_leaf": "#00641e",
      "bonsai_canopy": "#001e0a",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#00641e",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#00ff41"
    }
  },
  {
    "id": "crt-cyan",
    "label": "CRT Cyan",
    "group": "Crt",
    "kind": "CrtCyan",
    "colors": {
      "bg_canvas": "#000a0f",
      "bg_selection": "#009b9b",
      "bg_highlight": "#00141e",
      "border_dim": "#006478",
      "border": "#00ffff",
      "border_active": "#c8ffff",
      "text_faint": "#006478",
      "text_dim": "#00ffff",
      "text_muted": "#00b4c8",
      "text": "#32e6ff",
      "text_bright": "#c8ffff",
      "amber": "#00ffff",
      "amber_dim": "#005064",
      "amber_glow": "#dcffff",
      "chat_body": "#32e6ff",
      "chat_author": "#00ffff",
      "mention": "#ffffff",
      "success": "#00ffff",
      "error": "#ff5050",
      "bot": "#00ffff",
      "bonsai_sprout": "#00ffff",
      "bonsai_leaf": "#006478",
      "bonsai_canopy": "#00141e",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#006478",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#00ffff"
    }
  },
  {
    "id": "crt-c64",
    "label": "CRT C64",
    "group": "Crt",
    "kind": "CrtC64",
    "colors": {
      "bg_canvas": "#4040e0",
      "bg_selection": "#3c3c9b",
      "bg_highlight": "#2020a0",
      "border_dim": "#7878ff",
      "border": "#a0a0ff",
      "border_active": "#ffffff",
      "text_faint": "#7878ff",
      "text_dim": "#a0a0ff",
      "text_muted": "#c8c8ff",
      "text": "#a0a0ff",
      "text_bright": "#ffffff",
      "amber": "#a0a0ff",
      "amber_dim": "#6464c8",
      "amber_glow": "#ffffff",
      "chat_body": "#a0a0ff",
      "chat_author": "#ffffff",
      "mention": "#ffffff",
      "success": "#a0a0ff",
      "error": "#ff6464",
      "bot": "#a0a0ff",
      "bonsai_sprout": "#a0a0ff",
      "bonsai_leaf": "#7878ff",
      "bonsai_canopy": "#2020a0",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#7878ff",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ffffff"
    }
  },
  {
    "id": "crt-blood",
    "label": "CRT Blood",
    "group": "Crt",
    "kind": "CrtBlood",
    "colors": {
      "bg_canvas": "#0a0000",
      "bg_selection": "#9b0000",
      "bg_highlight": "#1e0000",
      "border_dim": "#640000",
      "border": "#ff0000",
      "border_active": "#ff6464",
      "text_faint": "#640000",
      "text_dim": "#ff0000",
      "text_muted": "#b40000",
      "text": "#ff2828",
      "text_bright": "#ff6464",
      "amber": "#ff0000",
      "amber_dim": "#500000",
      "amber_glow": "#ff9696",
      "chat_body": "#ff2828",
      "chat_author": "#ff0000",
      "mention": "#ffffff",
      "success": "#ff0000",
      "error": "#ffff00",
      "bot": "#ff0000",
      "bonsai_sprout": "#ff0000",
      "bonsai_leaf": "#640000",
      "bonsai_canopy": "#1e0000",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#640000",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ff0000"
    }
  },
  {
    "id": "crt-appleii",
    "label": "CRT Apple II",
    "group": "Crt",
    "kind": "CrtAppleII",
    "colors": {
      "bg_canvas": "#0c0f0a",
      "bg_selection": "#559b00",
      "bg_highlight": "#191e14",
      "border_dim": "#506400",
      "border": "#b9ff00",
      "border_active": "#dcff96",
      "text_faint": "#506400",
      "text_dim": "#b9ff00",
      "text_muted": "#8cb400",
      "text": "#b9ff28",
      "text_bright": "#dcff96",
      "amber": "#b9ff00",
      "amber_dim": "#465a00",
      "amber_glow": "#e6ffc8",
      "chat_body": "#b9ff28",
      "chat_author": "#b9ff00",
      "mention": "#ffffff",
      "success": "#b9ff00",
      "error": "#ff3c00",
      "bot": "#b9ff00",
      "bonsai_sprout": "#b9ff00",
      "bonsai_leaf": "#506400",
      "bonsai_canopy": "#191e14",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#506400",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#b9ff00"
    }
  },
  {
    "id": "crt-plasma",
    "label": "CRT Plasma",
    "group": "Crt",
    "kind": "CrtPlasma",
    "colors": {
      "bg_canvas": "#140a00",
      "bg_selection": "#9b0000",
      "bg_highlight": "#280f00",
      "border_dim": "#823200",
      "border": "#ff6400",
      "border_active": "#ffb464",
      "text_faint": "#823200",
      "text_dim": "#ff6400",
      "text_muted": "#c85000",
      "text": "#ff8228",
      "text_bright": "#ffb464",
      "amber": "#ff6400",
      "amber_dim": "#642800",
      "amber_glow": "#ffc896",
      "chat_body": "#ff8228",
      "chat_author": "#ff6400",
      "mention": "#ffffff",
      "success": "#ff6400",
      "error": "#ffffff",
      "bot": "#ff6400",
      "bonsai_sprout": "#ff6400",
      "bonsai_leaf": "#823200",
      "bonsai_canopy": "#280f00",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#823200",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ff6400"
    }
  },
  {
    "id": "crt-paperwhite",
    "label": "CRT Paperwhite",
    "group": "Crt",
    "kind": "CrtPaper",
    "colors": {
      "bg_canvas": "#19191e",
      "bg_selection": "#646478",
      "bg_highlight": "#28282d",
      "border_dim": "#64646e",
      "border": "#dcdcf0",
      "border_active": "#ffffff",
      "text_faint": "#64646e",
      "text_dim": "#dcdcf0",
      "text_muted": "#a0a0aa",
      "text": "#c8c8d2",
      "text_bright": "#ffffff",
      "amber": "#dcdcf0",
      "amber_dim": "#50505a",
      "amber_glow": "#ffffff",
      "chat_body": "#c8c8d2",
      "chat_author": "#dcdcf0",
      "mention": "#ffffff",
      "success": "#dcdcf0",
      "error": "#ff6464",
      "bot": "#dcdcf0",
      "bonsai_sprout": "#dcdcf0",
      "bonsai_leaf": "#64646e",
      "bonsai_canopy": "#28282d",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#64646e",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#dcdcf0"
    }
  },
  {
    "id": "crt-mauve",
    "label": "CRT Mauve",
    "group": "Crt",
    "kind": "CrtMauve",
    "colors": {
      "bg_canvas": "#0f000f",
      "bg_selection": "#9b009b",
      "bg_highlight": "#1e001e",
      "border_dim": "#780078",
      "border": "#ff00ff",
      "border_active": "#ffb4ff",
      "text_faint": "#780078",
      "text_dim": "#ff00ff",
      "text_muted": "#c800c8",
      "text": "#ff50ff",
      "text_bright": "#ffb4ff",
      "amber": "#ff00ff",
      "amber_dim": "#640064",
      "amber_glow": "#ffdcff",
      "chat_body": "#ff50ff",
      "chat_author": "#ff00ff",
      "mention": "#ffffff",
      "success": "#ff00ff",
      "error": "#00ffff",
      "bot": "#ff00ff",
      "bonsai_sprout": "#ff00ff",
      "bonsai_leaf": "#780078",
      "bonsai_canopy": "#1e001e",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#780078",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#ff00ff"
    }
  },
  {
    "id": "crt-pipb-mojave",
    "label": "CRT Pip-B Mojave",
    "group": "Crt",
    "kind": "CrtPipbMojave",
    "colors": {
      "bg_canvas": "#050a05",
      "bg_selection": "#009b2f",
      "bg_highlight": "#0a140a",
      "border_dim": "#0a7846",
      "border": "#12ff93",
      "border_active": "#c8ffdc",
      "text_faint": "#0a7846",
      "text_dim": "#12ff93",
      "text_muted": "#0fb464",
      "text": "#19ffa0",
      "text_bright": "#c8ffdc",
      "amber": "#12ff93",
      "amber_dim": "#055028",
      "amber_glow": "#dcffeb",
      "chat_body": "#19ffa0",
      "chat_author": "#12ff93",
      "mention": "#ffffff",
      "success": "#12ff93",
      "error": "#ff3c3c",
      "bot": "#12ff93",
      "bonsai_sprout": "#12ff93",
      "bonsai_leaf": "#0a7846",
      "bonsai_canopy": "#0a140a",
      "bonsai_bloom": "#ffffff",
      "badge_bronze": "#0a7846",
      "badge_silver": "#d1d1d1",
      "badge_gold": "#12ff93"
    }
  }
];
